### PR TITLE
Made app working again

### PR DESCRIPTION
**Pull request by kerastinell**
I've implemented some fixes without which the app wasn't working properly. Also I added a comment for every commit with the brief explanation of changes.

I guess the only things left to do are to update version name and upload the new APKs.

### CODE REVIEW

**Comment by Atulin** [comment]
Honestly, I'd suggest making a fork rather than making a pull request. Doesn;t seem like either of the Derpibooru repos are actively maintained.

**Comment by Atulin** [comment]
Okay, built the app, signed it with a temporaty key, it's working perfectly. Now all it needs is swiping and dark theme 🤣

**Comment by kerastinell** [comment]
Thank you for merging my pull request, @auzbuzzard. 
About 2 weeks ago I saw some fork on this repository addressing inability to login, but sadly I can't find it anymore. If the issue still persists, please let me know.

@Atulin I will look into what could be done about dark theme and swiping on the weekend, but I can't really promise to deliver it, sorry. The first reason is that I dropped Android developing back in Jellybean (Android 4.3) times and it will not be easy for me to adapt to the new framework. The second reason is my language barrier which kicks in sometimes, making me struggle with writing understandable code comments and expressing my thoughts.

**Comment by Atulin** [comment]
Sure thing, take your time. I'm not in any real hurry since AnimeBoxes added support for Derpibooru API token. No upvoting, favouriting, etc. but I can at least browse all images 👌

**Pull request merged**
